apiVersion: v1
kind: Secret
metadata:
    name: bookstack-admin-secret
    namespace: bookstack-prod
type: Opaque
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:IIL3SxezYlZTclMMZ2rsfw==,iv:bbDbRx7BGIjHd1oHtnA20IvuR+zQ4+SpcsngSyjR4+8=,tag:m7AB8iNzA+1S/Ve79Kl90g==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:deBc0a+vNU+FuA0j6mLgcw==,iv:TaW88wh2BOsofhFc+ZSfD8IEHowoJeWAi4uuLYNhPVY=,tag:t+ppqr+NAoqZ0k5EfdmI0A==,type:str]
sops:
    age:
        - recipient: age137504yr9n8n7acr49una4m4jyk9fet36jsnlct0su6vf9v5zyvesznvz6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMlpWM2wrVFdCKzRzMnJi
            VmxwNUlzUzdmaHFrWk0rVGxxV1JyWHVNRW1RCmg1OWNRLzVoZmU5SE5TYkhQbTNX
            d2s0NlU0VExlVkg3MlYxczFEOTdodjQKLS0tIGhpYUtaZzYxNEFScHhSaittRDBM
            b0t2QU9mbWJZaEdPTWYwdkN1TU9mN00KQYnXZxaA6bCbyCPjlWmrfvsVgwiJ7K7f
            3nv2KBR+aqgzOIKe8Y1ZIYmAHs4uVh7nv3wu/+AImKkg9/p5CV4Sjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T21:57:04Z"
    mac: ENC[AES256_GCM,data:yRzy4Kj8FERotAKWTG0wBo/Dk/+JWpclitUAcz4ZkHWZwvzveheRteoskpvI6v6u11YnFEXgTjg543UT85vtp5khaKHvsbUhPXsqLWbv+7kK8aqcicrsUYt8ir2+mfkLGMgig8d5lUfwJ82ZuuAVCwZRAtJMBdResbrEftXApYA=,iv:Nmr0BLH9J5pCYp/JkF22cZyEEJN1mj5Br7+NsFuoK6k=,tag:LaN9trRlx9qp2/yLkyNrgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
