apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstack-prod

resources:
- ../../base
- ingress.yaml
- resourcequota.yaml
- networkpolicy.yaml

patchesStrategicMerge:
- bookstack-url.patch.yaml

# workflow remplacera par ACR_LOGIN_SERVER + sha-<commit>
images:
- name: bookstack
  newName: idariusrncpacr6ykn7.azurecr.io/bookstack
  newTag: sha-51397deb2abf270a76b51ce13652c99a0133b653
