apiVersion: v1
kind: Secret
metadata:
    name: bookstack-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:L2zqkO9sLGM=,iv:mqXNTwaLeOTdubC63RoxY+Vz28HhXUvB3qOQArTFY2A=,tag:dqXvZfiHzXYOSaPPi6zNkA==,type:comment]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:6JHZBzkCJCaUiRsTNDnkxEBX,iv:zE9BwsO2svbO78veesJFjurAuQcAhdvvHNEWjDrB80s=,tag:SscV31L4o3Q2X9bXjSunGQ==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:Hy0glOchvtoY,iv:yj6JrbmcnYQonytqpaWpHqTsro0m/tWL7xA095d2lNU=,tag:A5OSaDYKVlAh07dGh2W2Gw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:ouqns0rf9Cwm,iv:dj7lREUskn+HzhzCYvhukYV2iB6HRqYT6rIr4WrIpoA=,tag:io/bXC00NARfVnzaS16+xw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:tBZjKSf2Dilp4w6/Ym+zv1gteg==,iv:e2QyMFoviMjXnYzlED1cUCb96s+sVhmcqVmuMnDY84E=,tag:uF9+5A6Sv/2O+7mN6YK3kQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:jQ/BVSL8TkNroRaPS0t7ay7whTyGx32eGBkamM2YtBvR1BnvqMwPSJltaB6yCXAZAhc7,iv:w4fj1SyoeiRTSNI7hhSVLulOdEWWjIWUoGmO9lNkiDY=,tag:DqbxV2XJ7YLLudW7K+klOg==,type:str]
sops:
    age:
        - recipient: age137504yr9n8n7acr49una4m4jyk9fet36jsnlct0su6vf9v5zyvesznvz6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRURpMVN0dDVQTWEzTnUr
            bGFlT3FueHF2d3V3ODg5ZzBBQWlWb2N0d0MwCkVuZ1RpR1NFMkIxSy9CaGVLb0ZW
            OXJxQTlvMW9aTFFuNjdXNnRpRzdSNWsKLS0tIExPYWtvYVN4QzNtdDhxRkd3UkhZ
            UjdESDhmbjdlb1hFRko1NktIQk5TdnMKDc0Q+8CFI07gCgPDSjM7qkkIdBDc/P9l
            PIC1AJI+5bXQznTrofrXriV4qyvGhm+FM4iy4ehZseVzbrg16zIpMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T14:40:32Z"
    mac: ENC[AES256_GCM,data:fcp5UGBn+HFTUOS3UxTbieTJ8VtFc4y4sbuCzCD1ZZNmY7fiiYgcN8HL45dcKQ37Rckkum56TEasrMwxy1p4AphbXjM3C70/TsB4uehFfxbQfp8LbHF2Uo0t1rZCc+FHiHeBaCX6vKjFNDRiqA2ynfwldbSb9zSC/zt3ghHGVJA=,iv:ip9rCWhpUzL2kHpduQBIMSK/7z5zS83xIDPfJO7JagE=,tag:VSlLJbfTuB9STdbsUF6TAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
