apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mariadb-pvc.yaml
  - mariadb-deployment.yaml
  - mariadb-service.yaml
  - bookstack-pvc.yaml
  - bookstack-deployment.yaml
  - bookstack-service.yaml

generators:
  - secret-generator.yaml
