apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bookstack-secrets.secret.sops.yaml
  - mariadb-pvc.yaml
  - mariadb-deployment.yaml
  - mariadb-service.yaml
  - bookstack-pvc.yaml
  - bookstack-deployment.yaml
  - bookstack-service.yaml
