apiVersion: v1
kind: Secret
metadata:
    name: bookstack-admin-secret
    namespace: bookstack-dev
type: Opaque
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:MpMBvZEnFf/gLtWv8iwx5g==,iv:vtjm78qjWPgjBAc4BfdA3otBA1x0HADn5B1SXA85BmQ=,tag:b2GyFiDMQPw1isObMYiyHQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:4O/GSyDKND0YppqMUdEdWA==,iv:tIO4/IlGCTkm8WO5KPG625k6a7CwwTJ1BCJ1X3hJq5U=,tag:bpi/JHkh1aGz65Kb4xcWuA==,type:str]
sops:
    age:
        - recipient: age137504yr9n8n7acr49una4m4jyk9fet36jsnlct0su6vf9v5zyvesznvz6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VTlUajBkeEN6eUUxeGJK
            aVQ5am10VXR5elRWamJBQWlYQURSdENTKzNzCmIzQkRPeHlscTJLL2FBRTJhbjZu
            Vm9BL1BMVWNUSDRSNmUxWk9sbGIzd3MKLS0tIFFpaG1MbjVHOXduc2R1OHJZMVdp
            OEdrQUZ2WTdlTmR3aUttcjBkZWdmNEEKJBb7FjcC/Mv6Jq0BMHGk9Bo9/QhnI6EA
            cHwuMczaw+KU+wd3WlWoDTQIDTh6PJ3X8vGIK5WIppRtzOTz/sji7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T21:56:57Z"
    mac: ENC[AES256_GCM,data:yxdPGCDhh8V87BhGHCveySq54iQ762wJp83KfMeXzHFV0SKozjLVP00s7Qr2Bz6Pk2sPXu99QuTmMWTF3wvZc5pffcFPH5QBfqnNAFaaHr+2FiBFPx+0L7LhMIIFjuYtDfmLSVEA7SRR/hdpkrlyv+OAt4rkcgUZQ8n5QK1V0A0=,iv:pipjbMWa9UO3SPafEof/WqA/SZMr3rNbDAPBtWcYrvE=,tag:q8+dUCvo2o/kumqcRN0t8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
