apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstack-dev

resources:
- ../../base
- ingress.yaml
- resourcequota.yaml
- networkpolicy.yaml

patchesStrategicMerge:
- bookstack-url.patch.yaml

# le workflow github remplacera par ACR_LOGIN_SERVER + sha-<commit>
images:
- name: bookstack
  newName: idariusrncpacr8k4ua.azurecr.io/bookstack
  newTag: sha-d41959fa2300b1884963b871e3c12333af9e8024
