apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstack-dev

resources:
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - bookstack-url.patch.yaml

# workflow remplacera par ACR_LOGIN_SERVER + sha-<commit>
images:
  - name: bookstack
    newName: lscr.io/linuxserver/bookstack
    newTag: version-v25.12.2
