apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstack-dev

resources:
- ../../base
- ingress.yaml

patchesStrategicMerge:
- bookstack-url.patch.yaml

# workflow remplacera par ACR_LOGIN_SERVER + sha-<commit>
images:
- name: bookstack
  newName: idariusrncpacrvpte4.azurecr.io/bookstack
  newTag: sha-deff86a910c7c66f0788842b3072e9090aa4896e
