apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstack-dev

resources:
- ../../base
- ingress.yaml

patchesStrategicMerge:
- bookstack-url.patch.yaml

# workflow remplacera par ACR_LOGIN_SERVER + sha-<commit>
images:
- name: bookstack
  newName: idariusrncpacru3lzt.azurecr.io/bookstack
  newTag: sha-8c46d0054bded43af82350552a9b2f6e710831b5
