apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstack-dev

resources:
  - ../../base
  - ingress.yaml
  - admin-secret.sops.yaml

patchesStrategicMerge:
  - bookstack-url.patch.yaml
  - admin-env.patch.yaml